//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int NumberAnswer { get; set; }
        public System.DateTime DateTimeAnswer { get; set; }
        public string AnswerOnRecall { get; set; }
        public int NumberRecallFK { get; set; }
        public int UserNumberFK { get; set; }
        public int IndividualNumberFK { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Recall Recall { get; set; }
    }
}
