//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recall
    {
        public Recall()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int NumberRecall { get; set; }
        public System.DateTime DateTime { get; set; }
        public string TypeRecall { get; set; }
        public string SubjectRecall { get; set; }
        public string TopicRecall { get; set; }
        public string Comment { get; set; }
        public int UserNumberFK { get; set; }
        public Nullable<int> NumberRoomFK { get; set; }
        public Nullable<int> IndividualNumberFK { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual HotelUser HotelUser { get; set; }
        public virtual Room Room { get; set; }
    }
}
