//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Recalls = new HashSet<Recall>();
        }
    
        public int NumberRoom { get; set; }
        public string TypeRoom { get; set; }
    
        public virtual ICollection<Recall> Recalls { get; set; }
    }
}
